### PR TITLE
Add click handler to open configured repo

### LINKED ISSUE #5: Access knob values in onclick handler
It would be cool for the GitHub stars component to open the configured repo in the browser on click via:

```python
@iterm2.RPC
def click_handler(session_id):
    repo = ...
    proc = await asyncio.create_subprocess_shell(
        f'open https://github.com/{repo}',
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
```

Unfortunately, the `repo` value is only available in the `knobs`, which can't be passed to the `onclick` coroutine. This is perhaps possible with some magic since the `@StatusBarRPC` coroutine does receive the knobs, but it was out of my reach.

### PR DESCRIPTION
**Pull request by harrygallagher4**
Here you go, fixes #5. I've never written python before so maybe some of this isn't good practice, but hey it works. Also, in the future, it would be cool to display the stars if the working directory is a github repo.

### CODE REVIEW

**Comment by daneah** [comment]
Thanks for this contribution! I'll give it a try sometime today if I can. I agree that showing the stars of the current repo you're in could be a pretty cool idea too. Feels like a separate component, or maybe a knob for this one.

**Comment by daneah** [comment]
Hey, so this works beautifully, functionally speaking. I'm going to have a look to see if the `global` can be got rid of; if not, I'm okay merging this in as-is for the moment!

**Comment by harrygallagher4** [comment]
#9

**Comment by daneah** [comment]
Guess it was [this](https://twitter.com/githubstatus/status/1138922728713523200) tripping me up!

**Pull request closed without merging**
